name: CI nodejs
on:
  - push
jobs:
  nodejs_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: '19'
      - run: echo "/node_modules" > .gitignore
      - run: cat "./.gitignore"
      - run: npm install
      - run: npm run lint