name: CI nodejs
on:
  - push
jobs:
  nodejs_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: echo "/node_modules" > .gitignore
      - run: cat "./.gitignore"
      - run: npm install
      - run: npm run lint